NERUDA = [
"I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.",
"I love you as certain dark things are to be loved, in secret, between the shadow and the soul.",
"Love is so short, forgetting is so long.",
"Well, now, If little by little you stop loving me, I shall stop loving you, Little by little, If suddenly you forget me, Do not look for me, For I shall already have forgotten you, If you think it long and mad the wind of banners that passes through my life, And you decide to leave me at the shore of the heart where I have roots, Remember, That on that day, at that hour, I shall lift my arms, And my roots will set off to seek another land",
"Someday, somewhere - anywhere, unfailingly, you'll find yourself, and that, and only that, can be the happiest or bitterest hour of your life. so I wait for you like a lonely house till you will see me again and live in me. Till then my windows ache. ",
"where I does not exist, nor you, so close that your hand on my chest is my hand, so close that your eyes close as I fall asleep.",
"I love you without knowing how, or when, or from where.",
"I love you straightforwardly, without complexities or pride; so I love you because I know no other way than this: I love you as the plant that never blooms but carries in itself the light of hidden flowers; thanks to your love a certain solid fragrance, risen from the earth, lives darkly in my body. I do not love you as if you were salt-rose, or topaz, or the arrow of carnations the fire shoots off. I love you as certain dark things are to be loved, in secret, between the shadow and the soul.",
"As if you were on fire from within.",
"The moon lives in the lining of your skin.",
"I want To do with you what spring does with the cherry trees.",
"I pace around hungry, sniffing the twilight, hunting for you, for your hot heart, Like a puma in the barrens of Quitratue.",
"I want to eat the sunbeam flaring in your lovely body, the sovereign nose of your arrogant face, I want to eat the fleeting shade of your lashes, ",
"I hunger for your sleek laugh, your hands the color of a savage harvest, hunger for the pale stones of your fingernails, I want to eat your skin like a whole almond. ",
"I crave your mouth, your voice, your hair. Silent and starving, I prowl through the streets. Bread does not nourish me, dawn disrupts me, all day I hunt for the liquid measure of your steps.",
"To feel the love of people whom we love is a fire that feeds our life.",
"Because of you, the heady perfumes of Summer pain me; because of you, I again Seek out the signs that precipitate desires: Shooting stars, falling objects.",
"Your caresses enfold me, like climbing Vines on melancholy walls.",
"Like a flower to its perfume, I am bound to My vague memory of you. I live with pain That is like a wound; if you touch me, you will Make to me an irreperable harm.",
"I have forgotten your voice, your happy voice; I have forgotten your eyes.",
"Because of you, I love the white statues, Drowsing in the parks, the white statues that, Have neither voice nor sight.",
"Because of you, in gardens of blossoming Flowers I ache from the perfumes of spring. I have forgotten your face, I no longer Remember your hands; how did your lips Feel on mine?",
"You are like nobody since I love you.",
"You can cut all the flowers but you cannot keep Spring from coming.",
"I can write the saddest poem of all tonight. I loved her, and sometimes she loved me too.",
"But I love your feet only because they walked upon the earth and upon the wind and upon the waters, until they found me.",
"my feet will want to walk to where you are sleeping but I shall go on living.",
"In this part of the story I am the one who dies, the only one, and I will die of love because I love you, because I love you, Love, in fire and in blood",
"We the mortals touch the metals, the wind, the ocean shores, the stones, knowing they will go on, inert or burning, and I was discovering, naming all the these things: it was my destiny to love and say goodbye.",
"In this part of the story I am the one who dies, the only one, and I will die of love because I love you, Because I love you, Love, in fire and blood. Maybe January light will consume my heart with its cruel ray, stealing my key to true calm.",
"I love you only because it's you the one I love; I hate you deeply, and hating you bend to you, and the measure of my changing love for you is that I do not see you but love you blindly. I do not love you except because I love you; I go from loving to not loving you, from waiting to not waiting for you my heart moves from cold to fire.", 
"That's why I love you and yet not why.",
"There are so many reasons, and yet so few, for love has to be so, involving and general, particular and terrifying, joyful and grieving, flowering like the stars, and measureless as a kiss.",
"If suddenly you do not exist, if suddenly you are not living, I shall go on living.",
"It was my destiny to love and say goodbye.",
"I got lost in the night, without the light of your eyelids, and when the night surrounded me, I was born again: I was the owner of my own darkness.",
"Next to the sea in the autumn, your laughter must raise its foamy cascade, and in the spring, love, I want your laughter like the flower I was waiting for, the blue flower, the rose of my echoing country.",
"My love, in the darkest hour your laughter opens, and if suddenly you see my blood staining the stones of the street, laugh, because your laughter will be for my hands like a fresh sword.",
"Do not take away the rose, the lance flower that you pluck, the water that suddenly bursts forth in joy, the sudden wave of silver born in you.",
"I love you without knowing how, or when, or from where, I love you simply, without problems or pride: I love you in this way because I don’t know any other way of loving.",

]
